
package menuutama;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;


public class dashboard extends javax.swing.JPanel {

    private DefaultTableModel model;
    
    public dashboard() {
        initComponents();
       
        transaksi();
        pesanan();
        totall();
        
        model = new DefaultTableModel();
        model.addColumn("Tanggal");
        model.addColumn("Total Harga");
        model.addColumn("Jenis Data");
        jTable1.setModel(model);
        rwyt();
    }
    
    private void rwyt(){
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "SELECT * FROM daily_data_view";
            
            try (PreparedStatement pst = c.prepareStatement(sql)) {
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    String tanggal = rs.getString("tanggal");
                    int totalHarga = rs.getInt("total_harga");
                    String jenisData = rs.getString("jenis_data");

                    Object[] rowData = {tanggal, totalHarga, jenisData};
                    model.addRow(rowData);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void transaksi(){
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT COUNT(*) AS jumlah_transaksi FROM transaksi WHERE DATE(tanggal) = CURDATE();";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                int tr = r.getInt("jumlah_transaksi");
                jLabel7.setText(String.valueOf(tr));
            }
            } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void pesanan(){
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT COUNT(*) AS jumlah_pesanan FROM pesanan WHERE DATE(tanggal) = CURDATE()";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                int tr = r.getInt("jumlah_pesanan");
                jLabel9.setText(String.valueOf(tr));
            }
            } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void totall(){
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM daily_total_view";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                int totalHarga = r.getInt("total_harga_hari_ini");
                
                DecimalFormat formatRibuan = new DecimalFormat("#,###");
                String formattedTotalHarga = formatRibuan.format(totalHarga);
                jLabel5.setText(formattedTotalHarga);
            }
            } catch (Exception e) {
            System.out.println(e.getMessage());
    }
    }
   
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 1120, 220));

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel5.setText("jLabel7");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 170, 50));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 110, 50));

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel10.setText("IDR");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 50));

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel9.setText("jLabel7");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, 120, 50));

        jLabel3.setFont(new java.awt.Font("DFPOP1-W9", 0, 18)); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Dokumen\\NetBeansProjects\\numnum\\src\\pct\\das.png")); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}