/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuutama;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class login extends javax.swing.JFrame {

    public static String username;
    public static String status;
    
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txusername = new javax.swing.JTextField();
        txpw = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txusername.setBackground(new java.awt.Color(238, 248, 235));
        txusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txusername.setBorder(null);
        txusername.setCaretColor(new java.awt.Color(238, 248, 235));
        txusername.setDisabledTextColor(new java.awt.Color(238, 248, 235));
        txusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txusernameFocusLost(evt);
            }
        });
        txusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txusernameMouseClicked(evt);
            }
        });
        getContentPane().add(txusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 148, 370, 50));

        txpw.setBackground(new java.awt.Color(238, 248, 235));
        txpw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txpw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txpw.setBorder(null);
        txpw.setCaretColor(new java.awt.Color(238, 248, 235));
        txpw.setDisabledTextColor(new java.awt.Color(238, 248, 235));
        txpw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txpwFocusLost(evt);
            }
        });
        getContentPane().add(txpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 265, 370, 50));

        login.setContentAreaFilled(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 320, 40));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 270, 40));

        jCheckBox1.setBorder(null);
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 332, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Dokumen\\NetBeansProjects\\numnum\\src\\pct\\login.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lupa Password ?");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
       try {
            String sql = "SELECT * FROM karyawan WHERE username='"+ txusername.getText()+"'AND password='" + txpw.getText()+"'";
            java.sql.Connection conn = (java.sql.Connection)koneksi.koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);

            if(rs.next()){
                if(txusername.getText().equals(rs.getString("username")) && txpw.getText().equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Login Berhasil, Silahkan Masuk");
                    
                    String idAkun = rs.getString("id_akun");
                    
                    // hak akses
                    status = rs.getString("level");
                    
                    username = txusername.getText();

                    // Set idAkun in SessionData
                    SessionData.setIdAkun(idAkun);
                    
                    // Instantiate pesanan 
                    menu_utama p = new menu_utama();

                    this.setVisible(false);
                    
                    p.setVisible(true);
                    // or t.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null,"Username Atau Password Yang Anda Masukkan Salah");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_loginActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
         if (jCheckBox1.isSelected()) {
            txpw.setEchoChar((char)0);
        } else {
            txpw.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void txusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txusernameFocusGained
        // TODO add your handling code here:
         String username = txusername.getText(); // untuk menghilangkan kata username saat kursor ditaruh text field username
        if(username.equals("Masukkan username")){
            txusername.setText("");
        }
    }//GEN-LAST:event_txusernameFocusGained

    private void txusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txusernameMouseClicked
        // TODO add your handling code here:
        int dialogResult = 0;
        if (txusername.getText().equals("username")){
            JOptionPane.showMessageDialog(null, "Tolong Masukkan Username");
        }
        else if(txpw.getText().equals("password")){
            JOptionPane.showMessageDialog(null, "Tolong Masukkan Password");
        }
    }//GEN-LAST:event_txusernameMouseClicked

    private void txusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txusernameFocusLost
        // TODO add your handling code here:
        String username = txusername.getText();    
        if(username.equals("")||username.equals("Masukkan username")){
            txusername.setText("Masukkan username");
        }
    }//GEN-LAST:event_txusernameFocusLost

    private void txpwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpwFocusLost
        // TODO add your handling code here:
        String password = txpw.getText();  
        if (password.equals("") || password.equals("Masukkan password")) {
            txpw.setText("Masukkan password");
        }
    }//GEN-LAST:event_txpwFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rfid x = new rfid();
        this.dispose();
        x.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
        jLabel2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        Sendcode sc = new Sendcode();
        this.setVisible(false);
        sc.setVisible(true);
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField txpw;
    private javax.swing.JTextField txusername;
    // End of variables declaration//GEN-END:variables
}
