
package menuutama;

import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import koneksi.koneksi;

public class menudonat extends javax.swing.JPanel {
    private final DefaultTableModel model;
    
    public menudonat() {
        initComponents();
        autonumber();
        model = new DefaultTableModel();
        tablemenudonat.setModel(model);
        model.addColumn("Id Menu");
        model.addColumn("Menu");
        model.addColumn("Harga");
        model.addColumn("Stok");
        loadtable(); 
     }
      
 public void cari() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID MENU");
        tabel.addColumn("MENU");
        tabel.addColumn("HARGA");
        tabel.addColumn("STOK");
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "Select * from menu where id_menu like '%" + txtcari.getText() + "%'" +
                    "or nama like '%" + txtcari.getText() + "%'";
            
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                });
            }
        tablemenudonat.setModel(tabel);
        loadtable();
        } catch (Exception e) {
            System.out.println(e.getMessage());
    } finally {
    }}
 
   private void autonumber(){
        try {
            java.sql.Connection c = koneksi.getKoneksi();
            java.sql.Statement s = c.createStatement();
            String sql = "SELECT * FROM menu ORDER BY id_menu DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String id_menu = r.getString("id_menu").substring(2);
                String MN = ""+(Integer.parseInt(id_menu)+1);
                String Nol = "";

               if (MN.length()==1)
                {Nol="0";}
               else if(MN.length()==2)
               {Nol="";}
                t_idmenu.setText("MN"+Nol+MN);
            } else{
                t_idmenu.setText("MN01");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
   
   
    
      private void loadtable(){
       model.getDataVector().removeAllElements();
       model.fireTableDataChanged();
       try {
         Connection c = (Connection) koneksi.getKoneksi();
            Statement s = (Statement) c.createStatement();
            
            String sql = "SELECT * FROM menu";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
                Object[] o = new Object[4];
                o [0] = r.getString("id_menu");
                o [1] = r.getString("nama");
                o [2] = r.getString("hargadnt");
                o [3] = r.getString("stok");
                
                model.addRow(o);
                
              
            }
           r.close();
           s.close();
       } catch (Exception e) {
           System.out.println(e.getMessage());
       }
    }

            
            private void Bersih(){
                autonumber();
                t_namamenu.setText("");
                t_hargamenu.setText("");
                t_stokmenu.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_namamenu = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        t_idmenu = new javax.swing.JTextField();
        t_stokmenu = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        b_simpanmenu = new javax.swing.JButton();
        t_hargamenu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tablemenu = new javax.swing.JScrollPane();
        tablemenudonat = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        barcode = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_namamenu.setBackground(new java.awt.Color(93, 113, 119));
        t_namamenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_namamenu.setBorder(null);
        t_namamenu.setCaretColor(new java.awt.Color(93, 113, 119));
        t_namamenu.setDisabledTextColor(new java.awt.Color(93, 113, 119));
        t_namamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namamenuActionPerformed(evt);
            }
        });
        t_namamenu.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                t_namamenuPropertyChange(evt);
            }
        });
        add(t_namamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 283, 230, 40));

        btn_refresh.setText("Refresh");
        btn_refresh.setContentAreaFilled(false);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 573, 80, 20));

        btnedit.setText(" Edit");
        btnedit.setContentAreaFilled(false);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 573, 80, 20));

        t_idmenu.setBackground(new java.awt.Color(93, 113, 119));
        t_idmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_idmenu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_idmenu.setBorder(null);
        t_idmenu.setCaretColor(new java.awt.Color(93, 113, 119));
        t_idmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idmenuActionPerformed(evt);
            }
        });
        add(t_idmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 230, 40));

        t_stokmenu.setBackground(new java.awt.Color(93, 113, 119));
        t_stokmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_stokmenu.setBorder(null);
        t_stokmenu.setCaretColor(new java.awt.Color(93, 113, 119));
        t_stokmenu.setDisabledTextColor(new java.awt.Color(93, 113, 119));
        t_stokmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_stokmenuActionPerformed(evt);
            }
        });
        add(t_stokmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 405, 230, 40));

        btnhapus.setText("Hapus");
        btnhapus.setContentAreaFilled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 573, 80, 20));

        b_simpanmenu.setBackground(new java.awt.Color(204, 204, 204));
        b_simpanmenu.setText("SIMPAN");
        b_simpanmenu.setContentAreaFilled(false);
        b_simpanmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanmenuActionPerformed(evt);
            }
        });
        add(b_simpanmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 140, 40));

        t_hargamenu.setBackground(new java.awt.Color(93, 113, 119));
        t_hargamenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_hargamenu.setBorder(null);
        t_hargamenu.setCaretColor(new java.awt.Color(93, 113, 119));
        t_hargamenu.setDisabledTextColor(new java.awt.Color(93, 113, 119));
        t_hargamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_hargamenuActionPerformed(evt);
            }
        });
        add(t_hargamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 342, 230, 40));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 95, 80));

        tablemenudonat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Menu", "Menu", "Harga", "Stok"
            }
        ));
        tablemenudonat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemenudonatMouseClicked(evt);
            }
        });
        tablemenu.setViewportView(tablemenudonat);

        add(tablemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 590, 320));

        txtcari.setBackground(new java.awt.Color(93, 113, 119));
        txtcari.setBorder(null);
        txtcari.setCaretColor(new java.awt.Color(93, 113, 119));
        txtcari.setDisabledTextColor(new java.awt.Color(93, 113, 119));
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });
        add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 175, 260, 27));

        barcode.setText("Barcode");
        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });
        add(barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Dokumen\\NetBeansProjects\\numnum\\src\\pct\\menufix.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -30, 1440, 840));
    }// </editor-fold>//GEN-END:initComponents

    private void t_namamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namamenuActionPerformed

    }//GEN-LAST:event_t_namamenuActionPerformed

    private void t_namamenuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_t_namamenuPropertyChange

    }//GEN-LAST:event_t_namamenuPropertyChange

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        Bersih();
        b_simpanmenu.setEnabled(true);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        b_simpanmenu.setEnabled(true);

        if (t_namamenu.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Pilih Dulu Data Yang Akan Diedit!");
        }else{

            {
                try {
                    String sql =( "update menu set nama='"+ t_namamenu.getText() +"' ,hargadnt='" +
                        t_hargamenu.getText()+ "',stok='" +
                        t_stokmenu.getText()+ "' where id_menu='" + t_idmenu.getText() + "'");
                    java.sql.Connection conn = (java.sql.Connection)koneksi.getKoneksi();
                    java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                    pst.execute();
                    loadtable();
                    Bersih();
                    JOptionPane.showMessageDialog(null,"Data Berhasil Diedit ");
                    t_namamenu.setEnabled(true);
                    t_hargamenu.setEnabled(true);
                    t_stokmenu.setEnabled(true);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

        }
        Bersih();
        loadtable();
    }//GEN-LAST:event_btneditActionPerformed

    private void t_idmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idmenuActionPerformed

    private void t_stokmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_stokmenuActionPerformed

    }//GEN-LAST:event_t_stokmenuActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed

        if (t_namamenu.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Dihapus!");

        }else{
            int jawab = JOptionPane.showConfirmDialog(null, "Data Ini Akan Dihapus, "
                + "Apakah anda Ingin Melanjutkannya?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    java.sql.Connection c = koneksi.getKoneksi();
                    java.sql.Statement s = c.createStatement();
                    String sql = "DELETE FROM menu WHERE id_menu = '" + t_idmenu.getText() + "'";
                    s.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    Bersih();
                    loadtable();
                    autonumber();
                    b_simpanmenu.setEnabled(true);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void b_simpanmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanmenuActionPerformed

        if (t_namamenu.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong!");

        }else{
            {
                try {
                    java.sql.Connection c = koneksi.getKoneksi();
                    java.sql.Statement s = c.createStatement();
                    String sql = "INSERT INTO menu VALUES ('"+t_idmenu.getText() +"','"+t_namamenu.getText() +"','"+t_hargamenu.getText()+"',"
                    + "'"+t_stokmenu.getText()+"')";
                    s.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Menu Berhasil Disimpan");
                    loadtable();

                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        Bersih();
        loadtable();
    }//GEN-LAST:event_b_simpanmenuActionPerformed

    private void t_hargamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_hargamenuActionPerformed

    }//GEN-LAST:event_t_hargamenuActionPerformed

    private void tablemenudonatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemenudonatMouseClicked
        t_idmenu.setText(tablemenudonat.getValueAt(tablemenudonat.getSelectedRow(), 0).toString());
        t_namamenu.setText(tablemenudonat.getValueAt(tablemenudonat.getSelectedRow(), 1).toString());
        t_hargamenu.setText(tablemenudonat.getValueAt(tablemenudonat.getSelectedRow(), 2).toString());
        t_stokmenu.setText(tablemenudonat.getValueAt(tablemenudonat.getSelectedRow(), 3).toString());
        b_simpanmenu.setEnabled(false);
    }//GEN-LAST:event_tablemenudonatMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtcariKeyReleased

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablemenudonat.getSelectedRow();
        if (selectedRow != -1) {
            this.setFocusable(false);
            String id = (String) tablemenudonat.getValueAt(selectedRow, 0);
            new Barcode(id).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris terlebih dahulu", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_barcodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_simpanmenu;
    private javax.swing.JButton barcode;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField t_hargamenu;
    private javax.swing.JTextField t_idmenu;
    private javax.swing.JTextField t_namamenu;
    private javax.swing.JTextField t_stokmenu;
    private javax.swing.JScrollPane tablemenu;
    private javax.swing.JTable tablemenudonat;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
