package menuutama;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

public class menu_item extends javax.swing.JPanel {
    
    public ArrayList<menu_item> getsubMenu(){
        return subMenu;
    }

    private final ArrayList<menu_item>subMenu = new ArrayList<>();
       
    private ActionListener act;

    public menu_item(Icon icon, boolean sbm, Icon IconSub, String menuName, ActionListener act, menu_item... subMenu) {
        initComponents();
        lb_subicon.setIcon(IconSub);
        lb_menuname.setText(menuName);
        lb_icon.setIcon(icon);
        lb_subicon.setVisible(sbm);
        
        if(act != null){
            this.act = act;
    }
        this.setSize(new Dimension (Integer.MAX_VALUE, 45)); 
        this.setMaximumSize(new Dimension (Integer.MAX_VALUE, 45)); 
        this.setMinimumSize(new Dimension (Integer.MAX_VALUE, 45)); 
        for (int i = 0; i < subMenu.length; i++) { 
        this.subMenu.add(subMenu [i]);
        subMenu[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_menuname = new javax.swing.JLabel();
        lb_subicon = new javax.swing.JLabel();
        lb_icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lb_menuname.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_subicon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_menuname, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_menuname, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(lb_subicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         setBackground(new java.awt.Color(204,204,204));
        if(showing){
            hideMenu();
        }else{
            showMenu();
        }
        if(act != null){
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        setBackground(new java.awt.Color(222,222,222));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_formMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_menuname;
    private javax.swing.JLabel lb_subicon;
    // End of variables declaration//GEN-END:variables
    private void hideMenu() {
        new Thread(new Runnable() {
        @Override
            public void run() {
                for (int i = subMenu.size()- 1; i >= 0; i--) {
                    sleep();
                    subMenu.get(i).setVisible(false); 
                    subMenu.get(i).hideMenu();
            }
            getParent().repaint();
            getParent().revalidate();
            showing = false;
            }
        }) .start();
    }
    private void showMenu() {
    new Thread (new Runnable() {
        @Override
        public void run() {
            for (int i = 0; i < subMenu.size(); i++) { 
                sleep();
                subMenu.get(i).setVisible(true);
            }
           showing = true;
           getParent().repaint();
           getParent().revalidate();
        }
    }) .start();
    }
    private void sleep() {
        try {
            Thread.sleep (20);
    } catch (Exception e) {
    }
   }

    
}
