
package menuutama;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.toedter.calendar.JDateChooser;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class pengeluaran extends javax.swing.JPanel {
    private final DefaultTableModel model;
    
    public pengeluaran() {
        initComponents();
         model = new DefaultTableModel();
        table.setModel(model);
        model.addColumn("Kode Pengeluaran");
        model.addColumn("Tanggal");
        model.addColumn("Keterangan");
        model.addColumn("Nominal");
        loadtable();   
        autonumber();
    }
    
    private void loadtable(){
       model.getDataVector().removeAllElements();
       model.fireTableDataChanged();
       try {
         Connection c = (Connection) koneksi.getKoneksi();
            Statement s = (Statement) c.createStatement();
            
            String sql = "SELECT * FROM pengeluaran";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
                Object[] o = new Object[4];
                o [0] = r.getString("kode_pengeluaran");
                o [1] = r.getString("tanggal");
                o [2] = r.getString("keterangan");
                o [3] = r.getString("nominal");
                
                model.addRow(o);
                
            }
           r.close();
           s.close();
       } catch (Exception e) {
           System.out.println(e.getMessage());
       }
    }
    
    private void bersih(){
        tanggals.setDate(null);
        txnominal.setText("");
        txket.setText("");
    }
    
    public void cari() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("kode pengeluaran");
        tabel.addColumn("tanggal");
        tabel.addColumn("keterangan");
        tabel.addColumn("nominal");
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "Select * from pengeluaran where kode_pengeluaran like '%" + tcari.getText() + "%'" +
                    "or keterangan like '%" + txnominal.getText() + "%'";
            
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                  
                });
            }
        table.setModel(tabel);
        loadtable();
        } catch (Exception e) {
            System.out.println(e.getMessage());
    } finally {
    }}
    
    private void autonumber() {
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pengeluaran ORDER BY kode_pengeluaran DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String kode = r.getString("kode_pengeluaran").substring(3);
                String TR = "" + (Integer.parseInt(kode) + 1);
                String Nol = "";

                if (TR.length() == 1) {
                    Nol = "000";
                } else if (TR.length() == 2) {
                    Nol = "00";
                } else if (TR.length() == 3) {
                    Nol = "0";
                } else if (TR.length() == 3) {
                    Nol = "";
                }
                txkoo.setText("KLR" + Nol + TR);
            } else {
                txkoo.setText("KLR0001");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
        private void kosong(){
        autonumber();
        tanggals.setDate(null);
        txnominal.setText("");
        txket.setText("");
        loadtable();
        btnsimpan.setEnabled(true);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        tanggals = new com.toedter.calendar.JDateChooser();
        tcari = new javax.swing.JTextField();
        txnominal = new javax.swing.JTextField();
        txkoo = new javax.swing.JTextField();
        txket = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 680, 130));

        btnhapus.setText("Hapus");
        btnhapus.setContentAreaFilled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 90, 20));

        btnrefresh.setText("Refresh");
        btnrefresh.setContentAreaFilled(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 90, 20));

        btnsimpan.setText("Simpan");
        btnsimpan.setContentAreaFilled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 120, 30));

        btnedit.setText("Edit");
        btnedit.setContentAreaFilled(false);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 90, 20));

        tanggals.setBackground(new java.awt.Color(93, 113, 119));
        tanggals.setForeground(new java.awt.Color(153, 153, 255));
        tanggals.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalsPropertyChange(evt);
            }
        });
        add(tanggals, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 230, 251, 50));

        tcari.setEditable(false);
        tcari.setBackground(new java.awt.Color(93, 113, 119));
        tcari.setBorder(null);
        tcari.setCaretColor(new java.awt.Color(93, 113, 119));
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcariKeyTyped(evt);
            }
        });
        add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 290, 40));

        txnominal.setBackground(new java.awt.Color(93, 113, 119));
        txnominal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txnominal.setBorder(null);
        txnominal.setCaretColor(new java.awt.Color(93, 113, 119));
        txnominal.setDisabledTextColor(new java.awt.Color(93, 113, 119));
        add(txnominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 357, 240, 38));

        txkoo.setBackground(new java.awt.Color(93, 113, 119));
        txkoo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txkoo.setBorder(null);
        txkoo.setCaretColor(new java.awt.Color(93, 113, 119));
        txkoo.setDisabledTextColor(new java.awt.Color(93, 113, 119));
        add(txkoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 171, 240, 40));

        txket.setBackground(new java.awt.Color(93, 113, 119));
        txket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txket.setBorder(null);
        txket.setCaretColor(new java.awt.Color(93, 113, 119));
        txket.setDisabledTextColor(new java.awt.Color(93, 113, 119));
        add(txket, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 293, 240, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Dokumen\\NetBeansProjects\\numnum\\src\\pct\\pengeluaran.png")); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1220, 830));
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        txkoo.setText(table.getValueAt(table.getSelectedRow(), 0).toString());
        txket.setText(table.getValueAt(table.getSelectedRow(), 2).toString());
        txnominal.setText(table.getValueAt(table.getSelectedRow(), 3).toString());
        try {
            // Parse the date string from the table and set it in the JDateChooser
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(table.getValueAt(table.getSelectedRow(), 1).toString());
            tanggals.setDate(date);
        } catch (Exception e) {
            e.printStackTrace(); // Handle the ParseException appropriately
        }
        btnsimpan.setEnabled(false);
    }//GEN-LAST:event_tableMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        if (txkoo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Dihapus!");

        }else{
            int jawab = JOptionPane.showConfirmDialog(null, "Data Ini Akan Dihapus, "
                + "Apakah anda Ingin Melanjutkannya?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    java.sql.Connection c = koneksi.getKoneksi();
                    java.sql.Statement s = c.createStatement();
                    String sql = "DELETE FROM pengeluaran WHERE kode_pengeluaran = '" + txkoo.getText() + "'";
                    s.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    kosong();
                    loadtable();
                    autonumber();
                    btnsimpan.setEnabled(true);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        loadtable();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        kosong();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        String kode = txkoo.getText();
        Date tanggal = tanggals.getDate();
        String ket = txket.getText();
        String nominal = txnominal.getText();

        try {
            Connection c = koneksi.getKoneksi();
            String sql = "INSERT INTO pengeluaran (kode_pengeluaran, tanggal, keterangan, nominal) VALUES (?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, kode);

            SimpleDateFormat outputFormat = new SimpleDateFormat("dd-MM-yyyy");
            String tanggalString = outputFormat.format(tanggal);

            Date parsedDate = outputFormat.parse(tanggalString);

            p.setDate(2, new java.sql.Date(parsedDate.getTime()));

            p.setString(3, ket);
            p.setString(4, nominal);

            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        bersih();
        loadtable();
        autonumber();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        btnsimpan.setEnabled(true);

    if (txkoo.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Pilih Dulu Data Yang Akan Diedit!");
    } else {
        try {
            // Formatter untuk tanggal dalam format ddMMyyyy
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = dateFormat.format(tanggals.getDate());

            String sql = "UPDATE pengeluaran SET tanggal = ?, keterangan = ?, nominal = ? WHERE kode_pengeluaran = ?";
            java.sql.Connection conn = (java.sql.Connection) koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, formattedDate); // Set the formatted date
            pst.setString(2, txket.getText());
            pst.setString(3, txnominal.getText());
            pst.setString(4, txkoo.getText());
            
            pst.execute();
            bersih();
            loadtable();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    }//GEN-LAST:event_btneditActionPerformed

    private void tanggalsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalsPropertyChange

    private void tcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyTyped
        cari();
    }//GEN-LAST:event_tcariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser tanggals;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField txket;
    private javax.swing.JTextField txkoo;
    private javax.swing.JTextField txnominal;
    // End of variables declaration//GEN-END:variables
}
