package menuutama;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

public class test extends javax.swing.JFrame {
    private final DefaultTableModel model;
    
    public test() {
        initComponents();
        model = new DefaultTableModel();
        jtable.setModel(model);
        model.addColumn("ID Pesanan");
        model.addColumn("Nama Customer");
        model.addColumn("Total");
        model.addColumn("Status");
        loadtable();
    }
    
    public void tampil() {
    try {
        Connection co = koneksi.getKoneksi();
        String sql = "SELECT * FROM pesanan WHERE id_pesanan LIKE '%" + txkode.getText() + "%'";
        PreparedStatement ps = co.prepareStatement(sql);
        ResultSet r = ps.executeQuery();
        
        // Declare variables outside the loop
        String tanggal = "";
        String status = "";
        String bayar = "";
        
        while (r.next()) {
            tanggal = r.getString("tanggal");
            status = r.getString("status_pembayaran");
            bayar = r.getString("bayar");
        }
        
        // Set GUI components with retrieved values
        txtanggal.setText(tanggal);
        cbstatus.setSelectedItem(status);
        txdp.setText(bayar);
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}

    
    public void cari() {
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID Pesanan");
    tabel.addColumn("Nama Customer");
    tabel.addColumn("Total");
    tabel.addColumn("Status");

    try {
        Connection c = koneksi.getKoneksi();
        String sql = "Select * from pesanan where id_pesanan like '%" + txtcari.getText() + "%'" +
                    "or nama_customer like '%" + txtcari.getText() + "%'";
        PreparedStatement p = c.prepareStatement(sql);
        ResultSet rs = p.executeQuery();

        // Process the ResultSet and add rows to the DefaultTableModel
        while (rs.next()) {
            String idPesanan    = rs.getString("id_pesanan");
            String namaCustomer = rs.getString("nama_customer");
            String totalHarga   = rs.getString("total_harga");
            String status       = rs.getString("status_pembayaran");
            
            // Add a row to the DefaultTableModel
            tabel.addRow(new Object[]{idPesanan, namaCustomer, totalHarga, status});
        }

        // Set the DefaultTableModel to your table
        jtable.setModel(tabel);

    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
    }
    
    public void loadtable(){
       model.getDataVector().removeAllElements();
       model.fireTableDataChanged();
       try {
         Connection c = (Connection) koneksi.getKoneksi();
            Statement s = (Statement) c.createStatement();
            
            String sql = "SELECT * FROM pesanan";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
                Object[] o = new Object[4];
                o [0] = r.getString("id_pesanan");
                o [1] = r.getString("nama_customer");
                o [2] = r.getString("total_harga");
                o [3] = r.getString("status_pembayaran");
                
                model.addRow(o);
                
              
            }
           r.close();
           s.close();
       } catch (Exception e) {
           System.out.println(e.getMessage());
       }
    }
    
    public void kosong(){
        txkode.setText("");
        txtanggal.setText("");
        cbstatus.setSelectedItem(null);
        txtotal.setText("");
        txdp.setText("");
        txsisa.setText("");
        txbayar.setText("");
        txkembalian.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        txkode = new javax.swing.JTextField();
        txtanggal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txdp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtotal = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        txsisa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txkembalian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txbayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        txtcari.setBackground(new java.awt.Color(93, 113, 119));
        txtcari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtcari.setForeground(new java.awt.Color(255, 255, 255));
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        btncari.setBackground(new java.awt.Color(93, 113, 119));
        btncari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncari.setForeground(new java.awt.Color(255, 255, 255));
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        txkode.setBackground(new java.awt.Color(93, 113, 119));
        txkode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txkode.setForeground(new java.awt.Color(255, 255, 255));

        txtanggal.setBackground(new java.awt.Color(93, 113, 119));
        txtanggal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtanggal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Kode pesanan");

        jLabel3.setText("Tanggal");

        txdp.setBackground(new java.awt.Color(93, 113, 119));
        txdp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txdp.setForeground(new java.awt.Color(255, 255, 255));
        txdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txdpFocusLost(evt);
            }
        });
        txdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txdpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txdpKeyTyped(evt);
            }
        });

        jLabel4.setText("Total");

        jLabel5.setText("Pembayaran sebelumnya");

        txtotal.setBackground(new java.awt.Color(93, 113, 119));
        txtotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtotal.setForeground(new java.awt.Color(255, 255, 255));
        txtotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtotalFocusLost(evt);
            }
        });
        txtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtotalKeyReleased(evt);
            }
        });

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));
        cbstatus.setEnabled(false);

        txsisa.setBackground(new java.awt.Color(93, 113, 119));
        txsisa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txsisa.setForeground(new java.awt.Color(255, 255, 255));
        txsisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txsisaKeyReleased(evt);
            }
        });

        jLabel6.setText("Sisa");

        txkembalian.setBackground(new java.awt.Color(93, 113, 119));
        txkembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txkembalian.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Kembalian");

        txbayar.setBackground(new java.awt.Color(93, 113, 119));
        txbayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txbayar.setForeground(new java.awt.Color(255, 255, 255));
        txbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbayarKeyReleased(evt);
            }
        });

        jLabel8.setText("Bayar");

        Simpan.setBackground(new java.awt.Color(93, 113, 119));
        Simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Simpan.setForeground(new java.awt.Color(255, 255, 255));
        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbstatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txkode, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txdp, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Simpan))
                            .addComponent(txsisa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(txbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncari, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtcari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txkode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txdp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txsisa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        cari();
    }//GEN-LAST:event_btncariActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        txkode.setText(jtable.getValueAt(jtable.getSelectedRow(), 0).toString());
        txtotal.setText(jtable.getValueAt(jtable.getSelectedRow(), 2).toString());
        tampil();
        try {
        // Mengambil nilai dari JTextField pertama dan kedua
        int nilai1 = Integer.parseInt(txtotal.getText());
        int nilai2 = Integer.parseInt(txdp.getText());
    
        // Melakukan operasi pengurangan
        int hasil = nilai1 - nilai2;
    
        // Menetapkan hasil pengurangan ke JTextField ketiga
        txsisa.setText(String.valueOf(hasil));
      } catch (NumberFormatException e) {
    // Tangani jika input tidak valid
    JOptionPane.showMessageDialog(null, "Masukkan angka yang valid di kedua kolom");
}
    }//GEN-LAST:event_jtableMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtcariKeyReleased

    private void txbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbayarKeyReleased
        // TODO add your handling code here:
        int sisa, bayar, kembalian;

        try {
            sisa = Integer.parseInt(txsisa.getText());
            String pay = txbayar.getText().trim();

        if (!pay.isEmpty()) {
            bayar = Integer.parseInt(pay);
            kembalian = bayar - sisa;
            cbstatus.setSelectedItem("Lunas");
        if (kembalian >= 0) {
            txkembalian.setText(String.valueOf(kembalian));
            cbstatus.setSelectedItem("Lunas"); // Assuming you want to set it to "Lunas" if kembalian >= 0
        } else {
            txkembalian.setText("0");
            cbstatus.setSelectedItem("Belum Lunas"); // Assuming you want to set it to "Belum Lunas" if kembalian < 0
        }
        } else {
        JOptionPane.showMessageDialog(null, "Masukkan jumlah bayar");
        }
        } catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Masukkan angka yang valid");
    }
    }//GEN-LAST:event_txbayarKeyReleased

    private void txdpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txdpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txdpKeyReleased

    private void txtotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotalKeyReleased

    private void txsisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txsisaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txsisaKeyReleased

    private void txdpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txdpKeyTyped
       
    }//GEN-LAST:event_txdpKeyTyped

    private void txdpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txdpFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txdpFocusLost

    private void txtotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtotalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotalFocusLost

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "update pesanan set bayar='" + txsisa.getText() + "', status_pembayaran='" +
            cbstatus.getSelectedItem().toString() + "' where id_pesanan='" + txkode.getText() + "'";
            java.sql.Connection conn = (java.sql.Connection) koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");
            kosong();
            loadtable();
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_SimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simpan;
    private javax.swing.JButton btncari;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable;
    private javax.swing.JTextField txbayar;
    private javax.swing.JTextField txdp;
    private javax.swing.JTextField txkembalian;
    private javax.swing.JTextField txkode;
    private javax.swing.JTextField txsisa;
    private javax.swing.JTextField txtanggal;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtotal;
    // End of variables declaration//GEN-END:variables
}
